### ISSUE TITLE
Clean up `/bot` command

### ISSUE THREAD

**Issue by swatarianess** [Project-Skill-Tree/Skill-Tree-Discord-Bot#103]
**Describe the bug**
There are some duplicate statistics, namely just `• servers` and `• Total servers`. Moreover, formatting of numbers would be nice for clarity. Using ` , ` or maybe showing 12345 as 12.35k or even with comma's for seperation (12,345). 

**To Reproduce**
1. Type `/bot` command

**Expected behavior**
There should not be duplicate statistics, as well as better formatting of large numbers.

For example: 
If the value of users is 88454, it should be formatted to 88.45k. Truncating the numbers making them clearing to read. 

For thousands: 88454 => 88.45k
For millions: 8845411 => 8,85m

**Screenshots**
![image](https://user-images.githubusercontent.com/1682734/184622691-85f943c2-4ab4-4732-af7d-0596a56eaa03.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A.

**Comment by Furkangunduz** [comment]
Hello you can use this function to format the big numbers.

    function bigNumberFormatter(num) {
        var dividersAndSymbols = [
            { value: 1E3, symbol: "K" },
            { value: 1E6, symbol: "M" },
        ];
        var regex = /\.0+$|(\.[0-9]*[1-9])0+$/;

        for (let i = dividersAndSymbols.length - 1; i > 0; i--) {
            if (num >= dividersAndSymbols[i].value) {
                return (num / dividersAndSymbols[i].value).toFixed(2).replace(regex, "$1") + 
                           dividersAndSymbols[i].symbol;
            }
        }
        return Math.floor(num)
    }

**Comment by Gamsti1337** [comment]
@swatarianess is this finished?

**Comment by Gamsti1337** [comment]
Working on it!
