### ISSUE TITLE
What are we doing?

### ISSUE THREAD

**Issue by swatarianess** [Project-Skill-Tree/Skill-Tree-Discord-Bot#33]
- [x] Figure out who will be the leaders of what initiatives
- [x] Set up the development environment
- [x] Set up where all of our documentation will be stored
   - [x] Set up public documentation
   - [ ] Set up private documentation

**Comment by seanjhardy** [comment]
We need private documentation and a better onboarding guide so that our developers can easily understand everything we've done. I've fully commented the code now so it should be easier to understand
