### ISSUE TITLE
Daily task list for current skills

### ISSUE THREAD

**Issue by swatarianess** [Project-Skill-Tree/Skill-Tree-Discord-Bot#37]

**Comment by seanjhardy** [comment]
- Needs to show character icon (from design team)
- needs to show XP
- needs to show badges (fake data until we have backend/coordinate with them about what the format will be)
- Needs to show item button to see all items (+item menu)

**Comment by seanjhardy** [comment]
- Must show skills along with their daily tasks
- Show the completion % of different skills (i.e. 25/31 meditation sessions complete)
- Daily reminders (make it optional, so someone can use "~remind 5PM" or something to get a daily reminder
- Anything else you can think of

**Comment by thewildofficial** [comment]
what will the daily reminders be based on?

**Comment by vlyr** [comment]
> what will the daily reminders be based on?

What do you mean?

**Comment by seanjhardy** [comment]
Completed
