### ISSUE TITLE
Skill tree command

### ISSUE THREAD

**Issue by seanjhardy** [Project-Skill-Tree/Skill-Tree-Discord-Bot#48]
- Must be able to view tree and figure out a way to let the user jump around easily (it shouldn't take 6 clicks to reach Fitness VI etc. Just think of a suitable format and make it work

**Comment by thewildofficial** [comment]
any updates on how this can be achieved?

**Comment by thewildofficial** [comment]
honestly we could have a system where there are some hardcoded JPEG "screens" that are made by design team, and a button/search system that cycles between the screens

**Comment by seanjhardy** [comment]
Effectively fixed as we've implemented the available skills menu, we will not be drawing the entire skill tree or let the user jump around
