### ISSUE TITLE
Server setup command to specify the channel to send weekly reports

### ISSUE THREAD

**Issue by seanjhardy** [Project-Skill-Tree/Skill-Tree-Discord-Bot#69]
**Is your feature request related to a problem? Please describe.**
Where will we send weekly reports in servers?

**Describe the solution you'd like**
Simple setup command for server admins to determine where bot messages will be sent

**Comment by thewildofficial** [comment]
i'm not really sure about  how we can describe this to the admin. 

maybe when the bot joins the discord server, it would go to the DMs of the owner and tell them they just need to go the channel and do a `~bind` command


`~bind` would just give the channel id to the DB, which would be used to send the user the message  if the `dms_enabled` clause fails. 

a possible problem is if a user is multiple servers which have skill tree, which channel would it send it in?
