### ISSUE TITLE
GuildMemberAdd just returns. Is this expected behavior?

### ISSUE THREAD

**Issue by swatarianess** [Project-Skill-Tree/Skill-Tree-Discord-Bot#85]
Issue: 
	GuildMemberAdd is not used, it just returns.
Solution:
	 Remove the file, unless it is supposed to do something, then remove the `return;`

![image](https://user-images.githubusercontent.com/1682734/179398998-11155ce6-fb97-4d63-a3a1-81d6a8db05fd.png)

**Comment by seanjhardy** [comment]
Will remove
